---
galaxy_info:
  role_name: kibana
  author: GR46
  description: Deploy Kibana 8.x for CIA observability
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: [jammy]
dependencies:
  - role: elasticsearch
