---
galaxy_info:
  role_name: filebeat
  author: GR46
  description: Install & configure Filebeat shipping to CIA Logstash
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: [jammy]
dependencies: []
