; Inventaire Site B (remote)
; 3 VMs : pfsense-s2, bastion-s2, services-s2 (forwarder / app mirror)

[pfsense]
pfsense-s2 ansible_host=192.168.0.1 ansible_user=admin ansible_port=22

[bastion]
bastion-s2 ansible_host=192.168.0.10 ansible_user=admin ansible_port=2222

[services]
services-s2 ansible_host=192.168.10.20 ansible_user=admin

[siteB:children]
pfsense
bastion
services

[linux:children]
bastion
services

[all:vars]
ansible_python_interpreter=/usr/bin/python3
site_id=2
site_name=siteB
