; Inventaire Site A (on-prem)
; 3 VMs : pfsense-s1, services-s1 (NetBox + webapp), observability-s1 (Elastic)
; Les IP sont alignées avec networking/addressing.yml.

[pfsense]
pfsense-s1 ansible_host=10.10.10.1 ansible_user=admin ansible_port=22

[services]
services-s1 ansible_host=10.10.10.20 ansible_user=admin

[observability]
observability-s1 ansible_host=10.10.10.40 ansible_user=admin

; --- Groupes logiques ---

[netbox:children]
services

[webapp:children]
services

[elastic:children]
observability

[kibana:children]
observability

[logstash:children]
observability

[siteA:children]
pfsense
services
observability

[linux:children]
services
observability

[all:vars]
ansible_python_interpreter=/usr/bin/python3
site_id=1
site_name=siteA
