# Filter SSH — succès / échecs bastion + autres Linux
filter {
  if [event][module] == "system" and [fileset][name] == "auth" {
    grok {
      match => { "message" => [
        "%{DATA:ssh_event} %{WORD:ssh_auth_method} for %{USER:ssh_user} from %{IP:ssh_src_ip} port %{INT:ssh_src_port} ssh2(: %{GREEDYDATA:ssh_extra})?",
        "Invalid user %{USER:ssh_user} from %{IP:ssh_src_ip} port %{INT:ssh_src_port}",
        "Disconnected from authenticating user %{USER:ssh_user} %{IP:ssh_src_ip} port %{INT:ssh_src_port}"
      ] }
      tag_on_failure => ["_grokparsefailure_ssh"]
    }
    if [ssh_event] == "Accepted" {
      mutate { add_tag => ["ssh_success"] }
    }
    if [ssh_event] == "Failed" {
      mutate { add_tag => ["ssh_failure"] }
    }
  }
}
