# Filter NetBox — parse l'audit log (JSON sur stdout Docker)
filter {
  if [container][name] == "netbox" or [program] == "netbox" {
    json {
      source => "message"
      target => "netbox"
      tag_on_failure => ["_jsonparsefailure_netbox"]
    }
    mutate {
      add_field => { "[event][module]" => "netbox" }
      add_field => { "[event][dataset]" => "netbox.audit" }
    }
  }
}
