# Output Elasticsearch — un index par dataset, ILM policy cia-30d
output {
  elasticsearch {
    hosts => ["http://127.0.0.1:9200"]
    user => "elastic"
    password => "${ELASTIC_ADMIN_PASSWORD}"
    index => "cia-%{[event][module]}-%{+YYYY.MM.dd}"
    ilm_enabled => true
    ilm_policy => "cia-30d"
    action => "create"
  }
}
