---
galaxy_info:
  role_name: dns-forwarder
  author: GR46
  description: Deploy unbound with conditional forwarding between CIA sites
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: [jammy]
dependencies: []
