---
galaxy_info:
  role_name: webapp
  author: GR46
  description: Internal CIA webapp portal, LAN-only
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: [jammy]
dependencies: []
