---
galaxy_info:
  role_name: elasticsearch
  author: GR46
  description: Deploy Elasticsearch 8.x single-node for CIA log_centralisation
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: [jammy]
dependencies: []
